### ISSUE TITLE
titlepage.svg must be correct height

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/selma-lagerlof_the-wonderful-adventures-of-nils_velma-howard#1]
See https://github.com/standardebooks/jules-verne_around-the-world-in-eighty-days_george-makepeace-towle/blob/master/images/titlepage.svg for a two-line title with one-line author and one-line translator.  You can copy and paste the viewbox info from there.

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/robinwhittleton/selma-lagerlof_the-wonderful-adventures-of-nils_velma-howard/commit/04b62c34433123a9011be0ae6e72c05d4961611e
