### ISSUE TITLE
Translator must be in <title> tag for cover.svg and titlepage.svg

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/selma-lagerlof_the-wonderful-adventures-of-nils_velma-howard#3]
See https://raw.githubusercontent.com/standardebooks/seneca_dialogues_aubrey-stewart/master/images/cover.svg for an example of `cover.svg`.  The `<title>` tag should be identical in `titlepage.svg`.

**Comment by acabal** [comment]
(Oops, not strictly _identical_, one will say "the cover" and one will say "the titlepage")

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/robinwhittleton/selma-lagerlof_the-wonderful-adventures-of-nils_velma-howard/commit/04b62c34433123a9011be0ae6e72c05d4961611e
