### ISSUE TITLE
Complete imprint.xhtml

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/selma-lagerlof_the-wonderful-adventures-of-nils_velma-howard#4]
Missing PG source link and IA link (switch Hathi Trust text to `the <a href="">Internet Archive</a>`).

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/robinwhittleton/selma-lagerlof_the-wonderful-adventures-of-nils_velma-howard/commit/652ecabfa715b3d651c00afee8763ae72ac94d28
